import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Chessboard } from "chessboard.slint";
import { MoveText } from "movetext.slint";

export global Callbacks {
    pure callback piece_from_fen(string, int) -> string;
    pure callback make_move(string, string, string) -> bool;
    pure callback color_on_square(string, string) -> string;
}

export component AppWindow inherits Window {
    title: "Openingheimer";
    full-screen: false;

    //start fen "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
    in-out property <string> fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
    in-out property <string> player_color;

    HorizontalBox {
        alignment: center;
        padding-top: 150px;

        Chessboard {
            fen: root.fen;
            player_color: root.player_color;
            piece_from_fen(f, i) => Callbacks.piece_from_fen(f, i);
            make_move(fen, start_square, end_square) => Callbacks.make_move(fen, start_square, end_square);
            color_on_square(f, square) => Callbacks.color_on_square(f, square);
        }

        MoveText { }
    }
}
