import { Button, VerticalBox } from "std-widgets.slint";
import { Chessboard } from "chessboard.slint";

export global Callbacks  {
    pure callback piece_from_fen(string, int) -> string;
    pure callback make_move(string, string, string) -> bool;
}

export component AppWindow inherits Window {
    title: "Openingheimer";
    full-screen: false;

    //in-out property <string> fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
    in-out property <string> fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
    in-out property <string> player_turn: "w";

    Chessboard {
      fen: root.fen;
      player_turn: root.player_turn;
      piece_from_fen(f, i) => Callbacks.piece_from_fen(f, i);
      make_move(fen, start_square, end_square) => Callbacks.make_move(fen, start_square, end_square);
    }
 }
