import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Chessboard } from "chessboard.slint";
import { SanMove, MoveRowItem } from "moverow.slint";
import { MoveText } from "movetext.slint";

export global Callbacks {
    pure callback piece_from_fen(string, int) -> string;
    pure callback make_move(string, string, string) -> bool;
    pure callback color_on_square(string, string) -> string;
    pure callback check_legal_move(string) -> bool;
    pure callback refresh_legal_moves(string, string, bool);
    pure callback go_to_position(SanMove);
}

export component AppWindow inherits Window {
    title: "Openingheimer";
    full-screen: is_full_screen;

    in-out property <string> fen:"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
    in-out property <string> player_color;
    in-out property <[MoveRowItem]> move_rows:  [
        {
            white: {
                id: "1",
                variation: "",
                san_text: "e4",
                fen: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1"
            },
            black: {
                id: "2",
                variation: "",
                san_text: "e5",
                fen: "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2"
            }
        },
        {
            white: {
                id: "3",
                variation: "",
                san_text: "Nf3",
                fen: "rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2"
            },
            black: {
                id: "4",
                variation: "",
                san_text: "Nc6",
                fen: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3"
            }
        },
        {
            white: {
                id: "5",
                variation: "",
                san_text: "Bb5",
                fen: "r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3"
            },
            black: {
                id: "6",
                variation: "",
                san_text: "a6",
                fen: "r1bqkbnr/1ppp1ppp/p1n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4"
            }
        }
    ];
    in-out property <[string]> legal_moves;
    in-out property <bool> is_full_screen: false;
    in-out property <string> current_move;

    HorizontalBox {
        alignment: center;
        padding-top: 150px;

        Chessboard {
            fen: root.fen;
            player_color: root.player_color;
            legal_moves: root.legal_moves;
            piece_from_fen(f, i) => Callbacks.piece_from_fen(f, i);
            make_move(fen, start_square, end_square) => Callbacks.make_move(fen, start_square, end_square);
            color_on_square(f, square) => Callbacks.color_on_square(f, square);
            check_legal_move(square) => Callbacks.check_legal_move(square);
            refresh_legal_moves(fen, square, clear) => Callbacks.refresh_legal_moves(fen, square, clear);
        }

        MoveText {
            move_rows: root.move_rows;
            current_move: root.current_move;
            go_to_position(m) => Callbacks.go_to_position(m);
        }
    }
}
