
export struct BoardSquare {
    coords: string,
    piece_color: string,
    square_color: color,
    image: image,
    has_piece: bool,
}

export component Chessboard {

    width: boardpx;
    height: boardpx;

    property <int> BOARD_SIZE: 600;

    in-out property <string> fen;
    in-out property <string> player_color;
    in-out property <bool> boardFlipped: false;

    property <length> boardpx: BOARD_SIZE * 1px;
    property <length> cellSize: (boardpx / 8);
    property <[string]> files: ["a", "b", "c", "d", "e", "f", "g", "h"];
    property <[string]> ranks: ["8", "7", "6", "5", "4", "3", "2", "1"];
    property <color> light: #EDD6B0;
    property <color> dark: #B88762;
    property <color> hightlight: #ffff33;

    property <string> active_coords;
    property <string> piece_in_hand_color;
    property <string> dropped_piece_coords;
    property <bool> is_grabbing_piece;

    pure callback piece_from_fen(string, int) -> string;
    pure callback make_move(string, string, string) -> bool;
    pure callback color_on_square(string, string) -> string;

    VerticalLayout {

        board := GridLayout {

            for rank[r] in ranks: Row {
                for file[f] in files: Rectangle {

                    property <BoardSquare> board_square: create_bs();

                    board_square_image := Image {
                        width: cellSize;
                        height: cellSize;
                        source: board_square.image;
                        visible: board_square.has_piece &&
                            (board_square.coords == active_coords && root.is_grabbing_piece) == false;
                    }

                    width: cellSize;
                    height: cellSize;
                    background: active_coords == board_square.coords && board_square.has_piece
                        ? board_square.square_color.mix(hightlight, 0.5)
                        : board_square.square_color;

                    TouchArea {
                        moved => {
                            dropped_piece_coords = get_hovered_square(self.mouse-x, self.mouse-y, f, r);

                            grab_piece(board_square, self.mouse-x, self.mouse-y, f, r)
                        }
                        pointer-event(event) => {
                            if (event.kind == PointerEventKind.down) {
                                if (event.button == PointerEventButton.right) {
                                    drop_piece();
                                }
                                else {
                                    pointer_down(board_square, self.mouse-x, self.mouse-y);
                                }
                            }
                            else if (event.kind == PointerEventKind.up) {
                                pointer_up(board_square);
                            }
                        };
                    }

                    function pointer_down(bs: BoardSquare, mousex: length, mousey: length) {

                        if (making_move(bs)) {
                            let made_move = make_move(fen, active_coords, bs.coords);

                            if made_move == false && bs.piece_color != player_color {
                                grab_piece(bs, mousex, mousey, f, r)
                            }
                        }
                        else {
                            grab_piece(bs, mousex, mousey, f, r);
                        }

                        active_coords = bs.coords;
                    }

                    function pointer_up(bs: BoardSquare) {

                        if (releasing_grabbed_piece(bs)) {
                            move_piece();
                        }
                        root.dropped_piece_coords = "";
                        root.is_grabbing_piece = false;
                    }

                    function create_bs() -> BoardSquare {
                        let fen_code = piece_from_fen(fen, f + (r * 8));

                        return {
                            coords: file + rank,
                            piece_color: color_on_square(fen, file + rank),
                            square_color: mod(f + r, 2) == 0 ? light : dark,
                            image: get_image(fen_code),
                            has_piece: fen_code != "."
                        };
                    }
                }
            }
        }
    }

    grabbed_piece := Image {
        width: cellSize;
        height: cellSize;
        visible: root.is_grabbing_piece;
    }

    function making_move(bs: BoardSquare) -> bool {
        bs.piece_color != player_color && our_piece()
    }

    function releasing_grabbed_piece(bs: BoardSquare) -> bool {
        root.is_grabbing_piece &&
            root.dropped_piece_coords != "" &&
            root.dropped_piece_coords != bs.coords
    }

    function grab_piece(bs: BoardSquare, mousex: length, mousey: length, file: int, rank: int) {

        root.is_grabbing_piece = true;
        grabbed_piece.source = bs.image;
        piece_in_hand_color = bs.piece_color;

        let board_coords = get_board_coords(mousex, mousey, file, rank);
        let imageOffset = cellSize / 2;

        let clamp_leeway_x = -imageOffset + board.x;
        let clamp_leeway_y = -imageOffset + board.y;

        grabbed_piece.x = clamp(board_coords.x - imageOffset + board.x, clamp_leeway_x, boardpx + clamp_leeway_x);
        grabbed_piece.y = clamp(board_coords.y - imageOffset + board.y, clamp_leeway_y, boardpx + clamp_leeway_y);
    }

    function move_piece() {

        let destination_color = color_on_square(fen, dropped_piece_coords);

        if (destination_color != player_color && our_piece()) {
            make_move(fen, active_coords, dropped_piece_coords)
        }
        else if (our_piece() == false) {
            active_coords = "";
        }
    }

    function drop_piece() {
        root.piece_in_hand_color = "";
        root.active_coords = "";
        root.is_grabbing_piece = false;
        root.dropped_piece_coords = "";
    }

    function get_hovered_square(mousex: length, mousey: length, file: int, rank: int) -> string {

        let board = get_board_coords(mousex, mousey, file, rank);

        let f = files[(board.x / (cellSize))];
        let r = ranks[(board.y / (cellSize))];

        f + r
    }

    function get_board_coords(x: length, y: length, f: int, r: int) -> Point {

        let bx = x + (f * cellSize);
        let by = y + (r * cellSize);

        { x: bx, y: by };
    }

    function our_piece() -> bool {
        piece_in_hand_color == player_color
    }

    function get_image(piece: string) -> image {
        if (piece == "P") { return @image-url("wp.png"); }
        if (piece == "N") { return @image-url("wn.png"); }
        if (piece == "B") { return @image-url("wb.png"); }
        if (piece == "R") { return @image-url("wr.png"); }
        if (piece == "Q") { return @image-url("wq.png"); }
        if (piece == "K") { return @image-url("wk.png"); }
        if (piece == "p") { return @image-url("bp.png"); }
        if (piece == "n") { return @image-url("bn.png"); }
        if (piece == "b") { return @image-url("bb.png"); }
        if (piece == "r") { return @image-url("br.png"); }
        if (piece == "q") { return @image-url("bq.png"); }
        if (piece == "k") { return @image-url("bk.png"); }
        @image-url("void.svg");
    }
}
