
import { BoardSquare } from "model.slint";

export component Chessboard {

    width: boardpx;
    height: boardpx;

    property <int> BOARD_SIZE: 600;

    in-out property <string> fen;
    in-out property <string> player_color;
    in-out property <bool> boardFlipped: false;

    property <bool> debug_legal_moves: false;
    in-out property <[string]> legal_moves;
    in-out property <string> last_move_from;
    in-out property <string> last_move_to;

    property <length> boardpx: BOARD_SIZE * 1px;
    property <length> cellSize: (boardpx / 8);
    property <[string]> files: ["a", "b", "c", "d", "e", "f", "g", "h"];
    property <[string]> ranks: ["8", "7", "6", "5", "4", "3", "2", "1"];
    property <color> light: #EDD6B0;
    property <color> dark: #B88762;
    property <color> hightlight: #ffff33;

    property <string> active_coords;

    property <string> piece_in_hand_color;
    property <string> dropped_piece_coords;
    property <bool> is_grabbing_piece;
    property <bool> off_board_x;
    property <bool> off_board_y;

    pure callback piece_from_fen(string, int) -> string;
    pure callback make_move(string, string, string) -> bool;
    pure callback color_on_square(string, string) -> string;
    pure callback check_legal_move(string) -> bool;
    pure callback refresh_legal_moves(string, string, bool);

    board := GridLayout {

        for rank[r] in ranks: Row {
            for file[f] in files: Rectangle {

                property <BoardSquare> board_square: create_bs();

                function create_bs() -> BoardSquare {
                    let fen_code = piece_from_fen(fen, f + (r * 8));
                    let coords = file + rank;

                    return {
                        coords: coords,
                        piece_color: color_on_square(fen, coords),
                        square_color: mod(f + r, 2) == 0 ? light : dark,
                        image: get_image(fen_code),
                        has_piece: fen_code != ".",
                        legal_move: check_legal_move(coords),
                    };
                }

                board_square_image := Image {
                    width: cellSize;
                    height: cellSize;
                    source: board_square.image;
                    visible: board_square.has_piece &&
                        (board_square.coords == active_coords && root.is_grabbing_piece) == false;
                }

                width: cellSize;
                height: cellSize;
                background: debugging_legal_moves() ? green :
                    ((active_coords == board_square.coords && board_square.has_piece) ||
                    last_move_from == board_square.coords ||
                    last_move_to == board_square.coords)
                    ? board_square.square_color.mix(hightlight, 0.5)
                    : board_square.square_color;

                TouchArea {
                    moved => {
                        dropped_piece_coords = get_hovered_square(self.mouse-x, self.mouse-y, f, r);

                        grab_piece(board_square, self.mouse-x, self.mouse-y, f, r)
                    }
                    pointer-event(event) => {
                        if (event.kind == PointerEventKind.down) {
                            if (event.button == PointerEventButton.right) {
                                drop_piece();
                            }
                            else {
                                pointer_down(board_square, self.mouse-x, self.mouse-y);
                            }
                        }
                        else if (event.kind == PointerEventKind.up) {
                            pointer_up(board_square);
                        }
                    };
                }

                function pointer_down(bs: BoardSquare, mousex: length, mousey: length) {

                    if (making_move(bs)) {
                        let made_move = make_move(fen, active_coords, bs.coords);

                        if made_move == false && bs.piece_color != player_color {
                            grab_piece(bs, mousex, mousey, f, r)
                        }
                    }
                    else {
                        grab_piece(bs, mousex, mousey, f, r);
                    }

                    active_coords = bs.coords;
                    display_legal_moves();
                }

                function pointer_up(bs: BoardSquare) {

                    if (releasing_grabbed_piece(bs)) {
                        move_piece();
                    }
                    soft_drop_piece();
                }

                function debugging_legal_moves() -> bool {
                    debug_legal_moves && board_square.legal_move
                }
            }
        }
    }

    grabbed_piece := Image {
        width: cellSize;
        height: cellSize;
        visible: root.is_grabbing_piece;
    }

    function making_move(bs: BoardSquare) -> bool {
        bs.piece_color != player_color && our_piece()
    }

    function releasing_grabbed_piece(bs: BoardSquare) -> bool {
        clear_legal_moves();
        root.is_grabbing_piece &&
            root.dropped_piece_coords != "" &&
            root.dropped_piece_coords != bs.coords
    }

    function grab_piece(bs: BoardSquare, mousex: length, mousey: length, file: int, rank: int) {

        root.is_grabbing_piece = true;
        grabbed_piece.source = bs.image;
        piece_in_hand_color = bs.piece_color;

        let board_coords = get_board_coords(mousex, mousey, file, rank);
        let imageOffset = cellSize / 2;

        let clamp_leeway_x = -imageOffset + board.x;
        let clamp_leeway_y = -imageOffset + board.y;

        grabbed_piece.x = clamp(board_coords.x - imageOffset + board.x, clamp_leeway_x, boardpx + clamp_leeway_x);
        grabbed_piece.y = clamp(board_coords.y - imageOffset + board.y, clamp_leeway_y, boardpx + clamp_leeway_y);
    }

    function move_piece() {

        let destination_color = color_on_square(fen, dropped_piece_coords);

        if (destination_color != player_color && our_piece()) {
            make_move(fen, active_coords, dropped_piece_coords)
        }
        else if (our_piece() == false) {
            active_coords = "";
        }
    }

    function drop_piece() {
        root.piece_in_hand_color = "";
        root.active_coords = "";
        soft_drop_piece();

        clear_legal_moves();
    }

    function soft_drop_piece() {
        root.dropped_piece_coords = "";
        root.is_grabbing_piece = false;
    }

    function get_hovered_square(mousex: length, mousey: length, file: int, rank: int) -> string {

        let board = get_board_coords(mousex, mousey, file, rank);

        let f = files[(board.x / (cellSize))];
        let r = ranks[(board.y / (cellSize))];

        f + r
    }

    function get_board_coords(x: length, y: length, f: int, r: int) -> Point {

        let bx = x + (f * cellSize);
        let by = y + (r * cellSize);

        dropped_off_board_hack(bx, by)
    }

    //fix crashes when grabbed piece is dropped off the board
    function dropped_off_board_hack(bx: length, by: length) -> Point {

        let off_left = bx < 0;
        let off_right = bx > BOARD_SIZE * 1px;
        let off_high = by < 0;
        let off_low = by > BOARD_SIZE * 1px;

        if (off_left || off_right) {
            off_board_x = true;
        }
        if (off_high || off_low) {
            off_board_y = true;
        }
        let x = off_board_x == false ? bx : off-left ? 0 : (BOARD_SIZE - 1) * 1px;
        let y = off_board_y == false ? by : off-high ? 0 : (BOARD_SIZE - 1) * 1px;

        off_board_x = false;
        off_board_y = false;

        { x: x, y: y }
    }

    function display_legal_moves() {
        if debug_legal_moves {
            refresh_legal_moves(fen, active_coords, false);
        }
    }

    function clear_legal_moves() {
        if debug_legal_moves {
            refresh_legal_moves(fen, active_coords, true);
        }
    }

    function our_piece() -> bool {
        piece_in_hand_color == player_color
    }

    function get_image(piece: string) -> image {
        if (piece == "P") { return @image-url("wp.png"); }
        if (piece == "N") { return @image-url("wn.png"); }
        if (piece == "B") { return @image-url("wb.png"); }
        if (piece == "R") { return @image-url("wr.png"); }
        if (piece == "Q") { return @image-url("wq.png"); }
        if (piece == "K") { return @image-url("wk.png"); }
        if (piece == "p") { return @image-url("bp.png"); }
        if (piece == "n") { return @image-url("bn.png"); }
        if (piece == "b") { return @image-url("bb.png"); }
        if (piece == "r") { return @image-url("br.png"); }
        if (piece == "q") { return @image-url("bq.png"); }
        if (piece == "k") { return @image-url("bk.png"); }
        @image-url("void.svg");
    }
}
