
export struct BoardSquare {
    coords: string,
    piece_color: string,
    square_color: color,
    image: image,
    has_piece: bool,
    legal_move: bool,
}

export struct SanMove {
    id: int,
    san_text: string,
    fen: string,
    previous_id: int,
    next_id: int,
    parent_line: int,
    variations: [int],
    hide_move: bool,
    variation_id: int,
    from_square: string,
    to_square: string
}

export struct SanMoveRow {
    white: SanMove,
    black: SanMove,
    turn: int,
    depth: int,
}

export struct PgnItem {
    filename: string,
    contents: string,
}
