
import {
    ListView,
    VerticalBox,
    HorizontalBox,
    ScrollView,
    Button,
} from "std-widgets.slint";

import { MoveRow } from "moverow.slint";
import { SanMoveRow, SanMove } from "model.slint";

export component MoveText {
    width: 450px;
    height: 450px;

    property <length> font_size: 16px;
    property <color> light: #454441;
    property <color> dark: #41403D;

    in property <[SanMoveRow]> move_rows;
    in-out property <SanMove> current_move;

    pure callback go_to_position(SanMove);
    pure callback go_to_move(int);
    callback scroll_to_index_y(int);
    callback scroll_to_index_x(int);

    scroll_to_index_y(index) => {
        scroll.viewport-y = -(index * 40px) + scroll.height / 2 - 20px;
    }

    scroll_to_index_x(x) => {
    }

    VerticalLayout {

        Rectangle {
            background: dark;

            scroll := ScrollView {

                property <color> font_color: #E7E2E6;

                VerticalLayout {

                    for move_row[i] in move_rows: HorizontalLayout {

                        height: 40px;

                        property <color> bg: mod(i, 2) == 0 ? dark : light;

                        MoveRow {
                            move: move_row;
                            background: bg;
                            current_move: root.current_move;
                            go_to_position(SanMove) => root.go_to_position(SanMove);
                        }
                    }
                }
            }
        }

        HorizontalLayout {
            padding-top: 10px;
            width: root.width / 2;
            x: (root.width - self.width) / 2;

            Rectangle {
                Button {
                    text: "<";
                    width: 100px;
                    clicked => root.go_to_move(current_move.previous_id);
                }
            }

            Rectangle {

                Button {
                    text: ">";
                    width: 100px;
                    clicked => root.go_to_move(current_move.next_id);
                }
            }
        }
    }
}
