
import {
    ListView,
    VerticalBox,
    HorizontalBox,
    ScrollView,
} from "std-widgets.slint";

import { MoveRow } from "moverow.slint";
import { SanMoveRow, SanMove } from "model.slint";

export component MoveText {
    width: 400px;
    height: 400px;

    property <length> font_size: 16px;
    property <color> light: #454441;
    property <color> dark: #41403D;

    in property <[SanMoveRow]> move_rows;
    in-out property <SanMove> current_move;

    pure callback go_to_position(SanMove);

    Rectangle {
        background: dark;

        scroll := ScrollView {
            viewport-y: scroll.height - scroll.viewport-height;

            property <color> font_color: #E7E2E6;

            VerticalLayout {

                for move_row[i] in move_rows: HorizontalLayout {

                    height: 40px;

                    property <color> bg: mod(i, 2) == 0 ? dark : light;

                    MoveRow {
                        move: move_row;
                        background: bg;
                        current_move: root.current_move;
                        go_to_position(SanMove) => root.go_to_position(SanMove);
                    }
                }
            }
        }
    }
}
