
import { SanMoveRow, SanMove } from "model.slint";

export component MoveRow {

    in-out property <SanMoveRow> move;
    in-out property <color> background;
    in-out property <SanMove> current_move;

    property <color> highlight_color: #A4B849;
    property <length> font_size: 16px;
    property <color> font_color: #E7E2E6;

    pure callback go_to_position(SanMove);

    height: 40px;

    HorizontalLayout {
        padding-right: 15px;

        Rectangle {
            width: (move.depth - 1) * 50px;
        }

        Rectangle {
            width: 40px;
            background: root.background;
            Text {
                x: 10px;
                text: move.turn + ".";
                font-size: font_size;
                width: 100%;
                color: move.blunder ? #DB0909 : font_color;
            }

            TouchArea {
                pointer-event(event) => {
                    select_move(event.kind, root.move.white);
                }
            }
        }

        Rectangle {
            background: root.background;
            width: 80px;
            Text {
                text: root.move.white.hide_move && root.move.white.id >= 0 ? "-" : root.move.white.san-text;
                font-size: font_size;
                width: 100%;
                color: move.white.id == current_move.id ? highlight_color : font_color;
            }

            TouchArea {
                pointer-event(event) => {
                    select_move(event.kind, root.move.white);
                }
            }
        }

        Rectangle {
            background: root.background;
            Text {
                text: root.move.black.hide_move && root.move.black.id >= 0 ? "-" : root.move.black.san-text;
                font-size: font_size;
                width: 100%;
                color: move.black.id == current_move.id ? highlight_color : font_color;
            }

            TouchArea {
                pointer-event(event) => {
                    select_move(event.kind, root.move.black);
                }
            }
        }

        function select_move(event_type: PointerEventKind, san_move: SanMove) {
            if (event_type == PointerEventKind.down) {
                go_to_position(san_move);
            }
        }
    }
}
