
export struct SanMove {
    id: string,
    variation: string,
    san_text: string,
    fen: string,
}

export struct MoveRowItem { white: SanMove, black: SanMove }

export component MoveRow {

    in-out property <MoveRowItem> move;
    in-out property <int> turn;
    in-out property <color> background;
    in-out property <string> current_move;

    property <color> highlight_color: #A4B849;
    property <length> font_size: 16px;
    property <color> font_color: #E7E2E6;

    pure callback go_to_position(SanMove);

    HorizontalLayout {

        Rectangle {
            width: 60px;
            background: root.background;
            Text {
                x: 10px;
                text: turn + ".";
                font-size: font_size;
                width: 100%;
            }

            TouchArea {
                pointer-event(event) => {
                    select_move(event.kind, root.move.white);
                }
            }
        }

        Rectangle {
            background: root.background;
            width: 140px;
            Text {
                text: root.move.white.san-text;
                font-size: font_size;
                width: 100%;
                color: move.white.id == current_move ? highlight_color : font_color;
            }

            TouchArea {
                pointer-event(event) => {
                    select_move(event.kind, root.move.white);
                }
            }
        }

        Rectangle {
            background: root.background;
            Text {
                text: root.move.black.san-text;
                font-size: font_size;
                width: 100%;
                color: move.black.id == current_move ? highlight_color : font_color;
            }

            TouchArea {
                pointer-event(event) => {
                    select_move(event.kind, root.move.black);
                }
            }
        }

        function select_move(event_type: PointerEventKind, san_move: SanMove) {
            if (event_type == PointerEventKind.down) {
                go_to_position(san_move);
            }
        }
    }
}
